version: '2'
services:
  meal-app: #app service / service name:
    build:
      context: '.'
      dockerfile: Dockerfile
    container_name: meal-app
    working_dir: /var/www/html

    ports:
      - "8009:80"
    volumes:
      - .:/var/www/html
  #      command: bash -c 'php artisan migrate && php artisan serve --host 0.0.0.0'

  #  command: bash -c 'php artisan serve --host 0.0.0.0'
  #   depends_on:
  #     - db
  #   links:
  #     - db
  # # db:
  # #   image: "mysql:5.7"
  # #   environment:
  # #     - MYSQL_ROOT_PASSWORD=mealPass  
  # #     - MYSQL_DATABASE=meal-system
  # #     - MYSQL_USER=root
  # #     - MYSQL_PASSWORD=mealPass
  # #   volumes:
  # #     - ./data/:var/lib/mysql
  # #   ports:
  # #     - "3306:3306"
  # # # phpmyadmin: 
  # # #   depends_on:
  # # #     - db
  # #   image: phpmyadmin/phpmyadmin
  # #   restart: always
  # #   ports:
  # #     - 8090:80
  # #   environment:
  # #     PMA_HOST: db
  # #     MYSQL_ROOT_PASSWORD: mealPass